version: "3.9"

services:
  app:
    build: .
    container_name: expense_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: expense_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: expense_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
